### ISSUE TITLE
Get the Javascript stack into a buildable state

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/open-corroborator-deploy#8]
Many of the js packages are out of date. It's not clear which ones can/should be updated, nor what the impact on the application would be.

The grunt build system itself fails to run (on ubuntu 14.04 at least) and so as a first step this needs upgrading. Initial attempts failed.

Without a working build system, changes to the 'front-end' application are blocked (other than i18n and data generated by the back-end).

**Comment by ggaughan** [comment]
Finally got 'grunt build' working locally and remotely via ansible and a delicate balance of package/npm versions (many of which are deprecated). It builds a specific language version though - so not sure how language switching is intended to work with a pre-built file per language. Probably needs another ticket: for now, for demos, will stick with the multiple js files (since I also checked that changing them does affect the app).
